# Generated by Django 2.1.4 on 2020-03-08 08:42

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('Preview', easy_thumbnails.fields.ThumbnailerImageField(default='students.jpg', upload_to='', verbose_name='Изображение')),
                ('Text', models.TextField(verbose_name='Текст')),
                ('Pub_date', models.DateField(verbose_name='Дата публикации')),
                ('File', models.FileField(blank=True, default=None, upload_to='uploads/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
            },
        ),
    ]
