# Generated by Django 2.1.4 on 2020-03-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('Preview', models.ImageField(blank=True, default=None, upload_to='', verbose_name='Превью статьи')),
                ('Text', models.TextField(verbose_name='Текст статьи')),
                ('Pub_date', models.DateField(verbose_name='Дата публикации')),
                ('File', models.FileField(blank=True, default=None, upload_to='uploads/', verbose_name='Прикрепить файл')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
