# Generated by Django 2.1.4 on 2020-03-06 08:55

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='File',
        ),
        migrations.AlterField(
            model_name='article',
            name='Preview',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='media/students.jpg', upload_to=''),
        ),
    ]
