# Generated by Django 2.1.4 on 2020-03-06 09:28

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('articles', '0003_auto_20200306_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Название контакта')),
                ('file', models.FileField(blank=True, default=None, upload_to='uploads/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='ArticleCategory',
        ),
        migrations.AlterField(
            model_name='article',
            name='Preview',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='media/students.jpg', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='file',
            name='Article',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
