# Generated by Django 2.1.4 on 2020-03-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200306_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Title',
            field=models.CharField(max_length=50, verbose_name='Название (Можно не указывать)'),
        ),
    ]
