# Generated by Django 2.1.4 on 2020-03-07 07:36

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200306_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=5, verbose_name='Год')),
                ('Image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Грамота',
                'verbose_name_plural': 'Грамоты',
            },
        ),
    ]
