# Generated by Django 2.1.4 on 2020-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='Year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
