# Generated by Django 2.1.4 on 2020-03-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200307_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория грамот',
                'verbose_name_plural': 'Категории грамот',
            },
        ),
        migrations.AddField(
            model_name='award',
            name='Category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.AwardCategory'),
        ),
    ]
