# Generated by Django 2.1.4 on 2020-03-06 13:50

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Название')),
                ('Image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AlterField(
            model_name='text',
            name='Title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
