# Generated by Django 2.1.4 on 2020-03-06 09:36

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('Preview', easy_thumbnails.fields.ThumbnailerImageField(default='media/students.jpg', upload_to='', verbose_name='Изображение')),
                ('Text', models.TextField(verbose_name='Текст')),
                ('Pub_date', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Разработка',
                'verbose_name_plural': 'Разработки',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Название контакта')),
                ('file', models.FileField(blank=True, default=None, upload_to='uploads/', verbose_name='Файл')),
                ('Article', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='devs.Development')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AddField(
            model_name='development',
            name='Category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='devs.DevelopmentCategory'),
        ),
    ]
