# Generated by Django 2.1.4 on 2020-03-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='Article',
            new_name='Development',
        ),
    ]
