# Generated by Django 2.1.4 on 2020-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0003_auto_20200306_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Title',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Название (Можно не указывать)'),
        ),
    ]
