# Generated by Django 2.1.4 on 2020-03-06 16:05

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0004_auto_20200306_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='Preview',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='students.jpg', upload_to='', verbose_name='Изображение'),
        ),
    ]
