# Generated by Django 2.1.4 on 2020-03-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0005_auto_20200306_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='Development',
        ),
        migrations.AddField(
            model_name='development',
            name='File',
            field=models.FileField(blank=True, default=None, upload_to='uploads/', verbose_name='Файл'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
