# Generated by Django 2.1.4 on 2020-03-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0007_auto_20200308_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentcategory',
            name='Title',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
    ]
